name: workflow27

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  ubuntu:

    strategy:

      fail-fast: false

      matrix:
        tag: ['24.04' ,'22.04', '20.04']
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [libbluray,libcaca,libcap,libcbor,libcddb,libcdio,libcerf,libcfitsio,libcgif,libcroco]

    runs-on: ubuntu-latest

    container: ubuntu:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v4

      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}

  alpine:
    if: false

    strategy:

      fail-fast: false

      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [libbluray,libcaca,libcap,libcbor,libcddb,libcdio,libcerf,libcfitsio,libcgif,libcroco]

    runs-on: ubuntu-latest

    container: alpine

    steps:
      - uses: actions/checkout@v4

      - run: wget https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}

  chroot-alpine:
    if: false

    strategy:

      fail-fast: false

      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [libbluray,libcaca,libcap,libcbor,libcddb,libcdio,libcerf,libcfitsio,libcgif,libcroco]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO http://dl-cdn.alpinelinux.org/alpine/v3.20/releases/x86_64/alpine-minirootfs-3.20.3-x86_64.tar.gz
      - run: install -d alpine-rootfs
      - run: tar xf alpine-minirootfs-3.20.3-x86_64.tar.gz -C alpine-rootfs
      - run: cp -p /etc/resolv.conf alpine-rootfs/etc/

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: mv ndk-pkg         alpine-rootfs/
      - run: mv ndk-pkg-install alpine-rootfs/

      - run: install -d alpine-rootfs/root/.ndk-pkg/repos.d/official-core/
      - run: mv formula alpine-rootfs/root/.ndk-pkg/repos.d/official-core/
      - run: |
            cat >       alpine-rootfs/root/.ndk-pkg/repos.d/official-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ndk-pkg-formula-repository-official-core
            branch: master
            pinned: 0
            enabled: 1
            created: 1673684639
            EOF

      - run: sudo mount -o bind  /dev alpine-rootfs/dev
      - run: sudo mount -t proc  none alpine-rootfs/proc
      - run: sudo mount -t sysfs none alpine-rootfs/sys

      - run: sudo chroot alpine-rootfs env GITHUB_ACTIONS=true ./ndk-pkg about
      - run: sudo chroot alpine-rootfs env GITHUB_ACTIONS=true ./ndk-pkg setup
      - run: sudo chroot alpine-rootfs env GITHUB_ACTIONS=true ./ndk-pkg sysinfo
      - run: sudo chroot alpine-rootfs env GITHUB_ACTIONS=true ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}


  macos:
    if: false

    strategy:

      fail-fast: false

      matrix:
        os:  [macos-14]
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [libbluray,libcaca,libcap,libcbor,libcddb,libcdio,libcerf,libcfitsio,libcgif,libcroco]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}
