name: workflow on ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: brew update
      run:  brew update

    - name: brew install 
      run:  brew install automake autoconf libtool pkg-config make cmake meson gperf itstool tree lzip nasm doxygen protobuf xmlto

    - name: install ndk-pkg
      run: |
        curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/master/bin/ndk-pkg
        chmod u+x ndk-pkg
        echo "$PWD" >> $GITHUB_PATH

    - name: set ANDROID_NDK_HOME environment variable
      run:  echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle" >> $GITHUB_ENV

    - name: ndk-pkg --version
      run:  ndk-pkg --version

    - name: ndk-pkg update
      run:  ndk-pkg update

    - name: ndk-pkg install all
      run:  ndk-pkg install all
